// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package determine

import (
	"omega/domain/base/basapi"
	"omega/domain/base/basrepo"
	"omega/domain/service"
	"omega/internal/core"
)

// Injectors from wire.go:

func initBasSettingAPI(e *core.Engine) basapi.BasSettingAPI {
	basSettingRepo := basrepo.ProvideBasSettingRepo(e)
	basSettingServ := service.ProvideBasSettingService(basSettingRepo)
	basSettingAPI := basapi.ProvideBasSettingAPI(basSettingServ)
	return basSettingAPI
}

func initBasRoleAPI(e *core.Engine) basapi.BasRoleAPI {
	basRoleRepo := basrepo.ProvideBasRoleRepo(e)
	basRoleServ := service.ProvideBasRoleService(basRoleRepo)
	basRoleAPI := basapi.ProvideBasRoleAPI(basRoleServ)
	return basRoleAPI
}

func initBasUserAPI(engine *core.Engine) basapi.BasUserAPI {
	basUserRepo := basrepo.ProvideBasUserRepo(engine)
	basUserServ := service.ProvideBasUserService(basUserRepo)
	basUserAPI := basapi.ProvideBasUserAPI(basUserServ)
	return basUserAPI
}

func initBasAuthAPI(e *core.Engine) basapi.BasAuthAPI {
	basAuthServ := service.ProvideBasAuthService(e)
	basAuthAPI := basapi.ProvideBasAuthAPI(basAuthServ)
	return basAuthAPI
}

func initBasActivityAPI(engine *core.Engine) basapi.BasActivityAPI {
	basActivityRepo := basrepo.ProvideBasActivityRepo(engine)
	basActivityServ := service.ProvideBasActivityService(basActivityRepo)
	basActivityAPI := basapi.ProvideBasActivityAPI(basActivityServ)
	return basActivityAPI
}
