// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"rest-gin-gorm/config"
	"rest-gin-gorm/pkg/invoice"
	"rest-gin-gorm/pkg/product"
	"rest-gin-gorm/pkg/user"
)

// Injectors from wire.go:

func initProductAPI(c config.CFG) product.ProductAPI {
	productRepository := product.ProvideProductRepostiory(c)
	productService := product.ProvideProductService(productRepository)
	productAPI := product.ProvideProductAPI(productService)
	return productAPI
}

func initInvoiceAPI(c config.CFG) invoice.InvoiceAPI {
	invoiceRepository := invoice.ProvideInvoiceRepostiory(c)
	invoiceService := invoice.ProvideInvoiceService(invoiceRepository)
	invoiceAPI := invoice.ProvideInvoiceAPI(invoiceService)
	return invoiceAPI
}

func initUserAPI(c config.CFG) user.UserAPI {
	userRepository := user.ProvideUserRepostiory(c)
	userService := user.ProvideUserService(userRepository)
	userAPI := user.ProvideUserAPI(userService)
	return userAPI
}
